### PR TITLE
Some bug fixes and some speed up

### PR DESCRIPTION
**Pull request by mboehme**

### CODE REVIEW

**Comment by mboehme** [comment]
Boosted from 60 execs/sec to 5k execs/sec :)

**Comment by dliyanage** [comment]
The changes look good to me Marcel. Let me trigger some trials on Nectar server.

**Comment by dliyanage** [comment]
@googlebot I consent.

**Comment by klainfo** [comment]
@googlebot I consent.

**Comment by dliyanage** [comment]
Since this works well enough, I am merging this PR with the master.

**Pull request merged**
