### PR TITLE
Updates to blackbox mode

### PR DESCRIPTION
**Pull request by mboehme**
* Better path count (only count coverage-increasing paths)
* Again keep track of coverage
* Store seeds in file system but don't add them to the queue

### CODE REVIEW

**Comment by mboehme** [comment]
Didn't try to compile :)

**Comment by dliyanage** [comment]
Thanks Marcel for the changes. 

When I was running the fuzzer version, I got the below error.

Screen Shot 2021-11-26 at 2 24 16 pm

I think the fuzzer is trying to save the same file again to the directory.

**Comment by mboehme** [comment]
Hi @dliyanage, I think I know what the problem was. Can you check again?

**Comment by dliyanage** [comment]
I've tested the updated code. I think it works fine. Below is a snapshot of the interface.

Screen Shot 2021-11-28 at 3 16 28 pm

Thanks Marcel.

**Comment by mboehme** [comment]
Awesome. You are welcome to merge.

**Comment by dliyanage** [comment]
Thanks Marcel. I'll merge now.

**Pull request merged**
